### PR TITLE
Initial commit.

### PR DESCRIPTION
**Pull request by harma051**
@EvanOman Solution file necessary for VS.

### CODE REVIEW

**Comment by EvanOman** [comment]
Soooo...can either of us merge the pull request? 

Also do you Pidgin bro?

**Comment by EvanOman** [comment]
@harma051

**Comment by harma051** [comment]
Heh, yes, technically either of us can merge it, proper procedure would be for you to do so.

**Comment by harma051** [comment]
My Pidgin download keeps breaking. I'm gonna try getting it on my work machine tomorrow.

**Pull request merged**
